version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env

  users:
    build:
      context: ./users-api
      dockerfile: User-Dockerfile
    container_name: user
    ports:
      - "8083:8083"
    env_file:
      - .env
    depends_on:
      - redis
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.users.entrypoints=websecure"
    #   - "traefik.http.routers.users.rule=Host(`users.bmp.com.ng`)"
    #   - "traefik.http.routers.users.tls.certresolver=mytls"

  auth:
    build:
      context: ./auth-api
      dockerfile: Auth-Dockerfile
    container_name: auth
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - users
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.auth.entrypoints=websecure"
    #   - "traefik.http.routers.auth.rule=Host(`auth.bmp.com.ng`)"
    #   - "traefik.http.routers.auth.tls.certresolver=mytls"

  todo:
    build:
      context: ./todos-api
      dockerfile: Todo-Dockerfile
    container_name: todo
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      - auth
      - redis
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.todos.entrypoints=websecure"
    #   - "traefik.http.routers.todos.rule=Host(`todos.bmp.com.ng`)"
    #   - "traefik.http.routers.todos.tls.certresolver=mytls"

  log-processor:
    build:
      context: ./log-message-processor
      dockerfile: Log-Dockerfile
    container_name: log
    env_file:
      - .env
    depends_on:
      - todo
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Frontend-Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - log-processor
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.frontend.entrypoints=websecure"
    #   - "traefik.http.routers.frontend.rule=Host(`bmp.com.ng`)"
    #   - "traefik.http.routers.frontend.tls.certresolver=mytls"

  # traefik:
  #   image: traefik:v3.1.6
  #   container_name: traefik
  #   restart: unless-stopped
  #   command:
  #     - "--api.dashboard=true"
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--entrypoints.web.address=:80"
  #     - "--entrypoints.websecure.address=:443"
  #     - "--certificatesresolvers.mytls.acme.tlschallenge=true"
  #     - "--certificatesresolvers.mytls.acme.email=incriszluv@gmail.com"
  #     - "--certificatesresolvers.mytls.acme.storage=/letsencrypt/acme.json"
  #     - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
  #     - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    
  #   ports:
  #     - "80:80"
  #     - "443:443"

  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #     - "./letsencrypt:/letsencrypt"   

networks:
  default:
    name: devops_network
